name: Team Cowboy Event Messenger

on:
  schedule:
    # Run every day at 3:25/4:25 (DST) pm PST
    - cron:  '25 23 * * *'

jobs:
  Teamcowboy_Event_Messenger:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]


    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip       
          python3 -m pip install --upgrade requests
          python3 -m pip install --upgrade twilio
          python3 -m pip install --upgrade python-teamcowboy-api      
      - name: 
        env:
          MYTCUSERID: ${{ secrets.MYTCUSERID }}           
          MYPHONENUMBER: ${{ secrets.MYPHONENUMBER }}
          BENTCUSERID: ${{ secrets.BENTCUSERID }}
          BENPHONENUMBER: ${{ secrets.BENPHONENUMBER }}
          HARRYTCUSERID: ${{ secrets.HARRYTCUSERID }}
          HARRYPHONENUMBER: ${{ secrets.HARRYPHONENUMBER }}
          TEAMNAME: ${{ secrets.TEAMNAME }}
        run: |
          python3 ./eventmessenger.py ${{ secrets.TEAMNAME }} ${{ secrets.TCPRIVATEAPIKEY }} ${{ secrets.TCPUBLICAPIKEY }} ${{ secrets.TCUSERNAME }} ${{ secrets.TCPASSWORD }} ${{ secrets.TWILIOACCOUNTSID }} ${{ secrets.TWILIOAUTHTOKEN }} ${{ secrets.TWILIOPHONENUMBER }}
          