name: Team Cowboy Event Messenger

on:
  schedule:
    # Run every day at 4:25 pm PST
    - cron:  '/5 * * * *'

jobs:
  Teamcowboy_Event_Messenger:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]


    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip       
          python3 -m pip install --upgrade requests
          python3 -m pip install --upgrade twilio
          python3 -m pip install --upgrade python-teamcowboy-api      
      - name: 
        env:
          PRIVATEAPIKEY: ${{ secrets.TCPRIVATEAPIKEY }}
          PUBLICAPIKEY: ${{ secrets.TCPUBLICAPIKEY }} 
          USERNAME: ${{ secrets.TCUSERNAME }}
          PASSWORD: ${{ secrets.TCPASSWORD }}
          TWILIOACCOUNTSID: ${{ secrets.TWILIOACCOUNTSID }}
          TWILIOAUTHTOKEN: ${{ secrets.TWILIOAUTHTOKEN }}
          TWILIOPHONENUMBER: ${{ secrets.TWILIOPHONENUMBER }}
          MYPHONENUMBER: ${{ secrets.MYPHONENUMBER }}
          BENPHONENUMBER: ${{ secrets.BENPHONENUMBER }}
          TEAMNAME: ${{ secrets.TEAMNAME }}
        run: |
          python3 ./eventmessenger.py TEAMNAME PRIVATEAPIKEY PUBLICAPIKEY USERNAME PASSWORD TWILIOACCOUNTSID TWILIOAUTHTOKEN TWILIOPHONENUMBER
          